-- MySQL Script generated by MySQL Workbench
-- Сб 26 авг 2017 21:26:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smarket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smarket` ;

-- -----------------------------------------------------
-- Schema smarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smarket` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `smarket` ;

-- -----------------------------------------------------
-- Table `smarket`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`users` ;

CREATE TABLE IF NOT EXISTS `smarket`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(64) NOT NULL COMMENT '',
  `salt` VARCHAR(45) NOT NULL COMMENT '',
  `enabled` TINYINT(1) NOT NULL COMMENT '',
  `telephone` VARCHAR(12) NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `telephone_UNIQUE` (`telephone` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`users_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`users_profiles` ;

CREATE TABLE IF NOT EXISTS `smarket`.`users_profiles` (
  `user_id` INT NOT NULL COMMENT '',
  `firsname` VARCHAR(45) NULL COMMENT '',
  `lastname` VARCHAR(45) NULL COMMENT '',
  `birthdate` DATE NULL COMMENT '',
  `gender` ENUM('male', 'female') NULL COMMENT '',
  `city` VARCHAR(45) NULL COMMENT '',
  `organization` VARCHAR(45) NULL COMMENT '',
  `avatar` BLOB NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  CONSTRAINT `fk_users_profiles_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `smarket`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`admins_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`admins_roles` ;

CREATE TABLE IF NOT EXISTS `smarket`.`admins_roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `role_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '',
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`organizations` ;

CREATE TABLE IF NOT EXISTS `smarket`.`organizations` (
  `org_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `owner_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`org_id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  INDEX `org_owner_fkey_idx` (`owner_id` ASC)  COMMENT '',
  CONSTRAINT `org_owner_fkey`
    FOREIGN KEY (`owner_id`)
    REFERENCES `smarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`events` ;

CREATE TABLE IF NOT EXISTS `smarket`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `charge_user_id` INT NOT NULL COMMENT '',
  `date_start` DATE NULL COMMENT '',
  `date_end` DATE NULL COMMENT '',
  `place` BLOB NULL COMMENT '',
  PRIMARY KEY (`event_id`)  COMMENT '',
  INDEX `event_charge_user_fkey_idx` (`charge_user_id` ASC)  COMMENT '',
  CONSTRAINT `event_charge_user_fkey`
    FOREIGN KEY (`charge_user_id`)
    REFERENCES `smarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`participations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`participations` ;

CREATE TABLE IF NOT EXISTS `smarket`.`participations` (
  `event_id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  UNIQUE INDEX `event_participation_index` (`event_id` ASC, `user_id` ASC)  COMMENT '',
  INDEX `participation_user_key_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `participation_event_key`
    FOREIGN KEY (`event_id`)
    REFERENCES `smarket`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `participation_user_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `smarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO smarket;
 DROP USER smarket;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'smarket' IDENTIFIED BY 'smarket';

GRANT ALL ON `smarket`.* TO 'smarket';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
