-- MySQL Script generated by MySQL Workbench
-- Sat Aug 25 20:22:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smarket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smarket` ;

-- -----------------------------------------------------
-- Schema smarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smarket` DEFAULT CHARACTER SET utf8 ;
USE `smarket` ;

-- -----------------------------------------------------
-- Table `smarket`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`users` ;

CREATE TABLE IF NOT EXISTS `smarket`.`users` (
  `user_id` BIGINT(11) GENERATED ALWAYS AS () VIRTUAL,
  `username` VARCHAR(25) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `telephone` VARCHAR(12) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telephone_UNIQUE` (`telephone` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`users_profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`users_profiles` ;

CREATE TABLE IF NOT EXISTS `smarket`.`users_profiles` (
  `user_id` BIGINT(11) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `gender` ENUM('male', 'female') NULL,
  `city` VARCHAR(45) NULL,
  `organization` VARCHAR(45) NULL,
  `avatar` BLOB NULL,
  `telegram_id` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `telegram_id_UNIQUE` (`telegram_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_profiles_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `smarket`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`admins_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`admins_roles` ;

CREATE TABLE IF NOT EXISTS `smarket`.`admins_roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`organizations` ;

CREATE TABLE IF NOT EXISTS `smarket`.`organizations` (
  `org_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `owner_id` BIGINT(11) NOT NULL,
  PRIMARY KEY (`org_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `org_owner_fkey_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `org_owner_fkey`
    FOREIGN KEY (`owner_id`)
    REFERENCES `smarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`events` ;

CREATE TABLE IF NOT EXISTS `smarket`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `charge_user_id` BIGINT(11) NOT NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `place` BLOB NULL,
  PRIMARY KEY (`event_id`),
  INDEX `event_charge_user_fkey_idx` (`charge_user_id` ASC) VISIBLE,
  CONSTRAINT `event_charge_user_fkey`
    FOREIGN KEY (`charge_user_id`)
    REFERENCES `smarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`participations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`participations` ;

CREATE TABLE IF NOT EXISTS `smarket`.`participations` (
  `event_id` INT NOT NULL,
  `user_id` BIGINT(11) NOT NULL,
  UNIQUE INDEX `event_participation_index` (`event_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `participation_user_key_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `participation_event_key`
    FOREIGN KEY (`event_id`)
    REFERENCES `smarket`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `participation_user_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `smarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`telegram_connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`telegram_connections` ;

CREATE TABLE IF NOT EXISTS `smarket`.`telegram_connections` (
  `user_id` BIGINT(11) NOT NULL,
  `telegram_id` INT NOT NULL,
  `verified` TINYINT(1) NOT NULL,
  PRIMARY KEY (`user_id`, `telegram_id`),
  CONSTRAINT `fk_telegram_connections_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `smarket`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`verification_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`verification_codes` ;

CREATE TABLE IF NOT EXISTS `smarket`.`verification_codes` (
  `source_system` ENUM('EMail', 'Telegram') NOT NULL,
  `verification_code` VARCHAR(7) NOT NULL,
  `valid_till` DATE NOT NULL,
  `target_id` VARCHAR(45) NOT NULL,
  `target_user_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`source_system`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smarket`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smarket`.`user` ;

CREATE TABLE IF NOT EXISTS `smarket`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

SET SQL_MODE = '';
GRANT USAGE ON *.* TO smarket;
 DROP USER smarket;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'smarket' IDENTIFIED BY 'smarket';

GRANT ALL ON `smarket`.* TO 'smarket';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
